### PR TITLE
docs: fixes grammatical, spelling and formatting errors for markdown …

### PR DESCRIPTION
**Pull request by lax0248917**
…files

Fixs any major grammatical, spelling, and formatting errors in both the markdwon files and the .tsx
files that display that text for each component

re #116

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)
 
## How Has This Been Tested?

Only testing that was done was that of which was already designed for the project.

Looks like most of these changes came from style formatting, which I am thinking was applied from my own environment. What would be necessary to revert those stylist changes back to match that of the rest of the project? All I am looking to change are the grammatical, spelling, and typo errors found in the markdown files, and the descriptions of the components. 

Appreciate your help as I am new to open source contributions.

### CODE REVIEW

**Comment by asifahmedfw** [comment]
Hey Zach!
Congratulations on your first PR in Crayons 🥳 
This looks good. For the style changes, I am guessing you are using a `prettier` in your editor and that is styling the code. You need to disable it for this project. If not, then maybe you have to check your code editor preferences again.

Also before committing, I would request you to build the components once via `npm run build:components`.

**Comment by lax0248917** [comment]
Hello @asifahmedfw,
You were correct, I did have prettier extension installed and running for this project. I disabled it and built the components prior to making the latest commit. I appreciate your help and feedback.

**Comment by asifahmedfw** [comment]
Hello @lax0248917, 
The PR still has a lot of changes to the code style. Can you revert them? Changes are there in Readme files for components and also multiple components.

**Comment by lax0248917** [comment]
Hello @asifahmedfw,
I'm sorry but I am not sure how to revert the style changes. Should I do something like `git revert <commitID>`? Or maybe squash the commits and start over with the prettier extension disabled? Haven't come across an editor issue like this before. Thank you so much for your guidance in this matter.

**Comment by asifahmedfw** [comment]
@lax0248917 The cleanest way is to start over in a new branch from base and with `prettier` disabled, make your content changes. I know it is a lot of work. I am really sorry. 😞 
Also before committing make sure you build it once.

**Comment by lax0248917** [comment]
@asifahmedfw,
No problem, I will make that happen. It was my fault for not disabling prettier in the beginning.
Thank you for the help.

**Comment by asifahmedfw** [comment]
Closing this as this has been replaced with #122

**Pull request closed without merging**
