### PR TITLE
[FC-125532] label_and _choices_input_fix

### PR DESCRIPTION
**Pull request by Srikannan-E**
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)

### CODE REVIEW

**Review by srivatsan7 — APPROVED** [review]
LGTM please test all the dropdown cases before merging

**Review by srivatsan7 — COMMENTED** [review]
Reverse merge latest changes

**Review by prasanna-vijayan — COMMENTED** [review]
Can you please list of cases how you did test this manually? 
Can you also test dependent field and dropdown with chat + crayons integrated locally?

**Review by prasanna-vijayan — APPROVED** [review]
Looks good to me.

**Review by rihansiddhi — APPROVED** [review]

**Pull request closed without merging**
