### PR TITLE
Feat | @fw/crayons-visual-regression

### PR DESCRIPTION
**Pull request by detiwari003**
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)

### CODE REVIEW

**Comment by detiwari003** [comment]
Dear All,
The command is " **npm i &&  npm run build** ".
**Note**: This is automated and the developer does not have to run any visual test separately. At the time of commit && push, the workflow will check for any visual regressions and then only proceed.PFA Screenshots.

push-ui-test
commit-ui-test

**Comment by detiwari003** [comment]
### Puppeteer Issues Solved

* Error: Navigation failed because browser has disconnected!   [Solved]
* Protocol error (Target.setDiscoverTargets): Target closed when puppeteer.launch fails   [Solved]
* [Puppeteer - MaxListenerExceedsWarning: Possible EventEmitter memory leak detected. page.close() and browser.close() not working [Solved]](https://stackoverflow.com/questions/61723184/puppeteer-maxlistenerexceedswarning-possible-eventemitter-memory-leak-detecte)
* Error: Protocol error (Page.captureScreenshot): Target closed.   [Solved]
* [Time out error when executing Jest test with puppeteer [Solved]](https://stackoverflow.com/questions/61537018/time-out-error-when-executing-jest-test-with-puppeteer)
* Session closed. Most likely the page has been closed   [Solved]
* UnhandledPromiseRejectionWarning: Error: Protocol error: Target closed   [Solved]
* Timeout - Async callback was not invoked within the 5000ms timeout not showing where it failed   [Solved]
* [Puppeteer: memory leak error and timeout handling [Solved]](https://stackoverflow.com/questions/67564324/puppeteer-memory-leak-error-and-timeout-handling)
* All tests taking more than 30 mins . Now within 5 mins - 7 mins.    [Solved]
* Editor or local machine got hanged up and went unresponsive after puppeeteer ran in local. [Solved]
* Restart of machne was required after each run .   [Solved]

**Review by arvindanta — CHANGES_REQUESTED** [review]
Why  do we need a separate package for visual regression. It's very much tied to the components with in crayons-core package. Can we just keep it with in `crayons-core` as a separate folder ?

**Comment by detiwari003** [comment]
> Why do we need a separate package for visual regression. It's very much tied to the components within the crayons-core package. Can we just keep it with in `crayons-core` as a separate folder?

Ans : This is an entirely separate and reusable entity. In future, I will code it into a CLI and separate the specs into crayons-core. This way, any package just need to pass the specs to CLI and it will work. We can port it to other teams as a utility.

**Comment by detiwari003** [comment]
This is now built into CI- Git- Pre-Push/Pre-Commit Hooks. Here are the screenshots for Success/Failure. E2E tests also run in paralllel.

e2e

**Comment by detiwari003** [comment]
**Running Jest Update** 
Use these two commands to update all snapshots :-
  1. "update-snapshots:all": "jest -u --testPathPattern=./__all_tests__/__tests__",
  2. "update-snapshots:each": "jest -u --testPathPattern=./__spec_test/__tests__",

However above two commands are rarely required as we only need to run jest update on failed specs after corrections.
Therefor run as follows:-
JEST-U

**Pull request closed without merging**
